#+title: Algebraic Geometry in Melbourne 
#+subtitle: 8--10 July 2026 
#+options: toc:1

#+begin_announcement
[[file:poster.pdf][Here is a poster (PDF, about 5 MB)]] to advertise this event.
#+end_announcement

* Venue
:PROPERTIES:
:UNNUMBERED: notoc
:END:
The University of Melbourne

* Speakers

- [[Dougal Davis]] (Melbourne)
- [[Gianluca Faraco]] (Monash)
- [[Christian Haesemeyer]] (Melbourne)
- [[Caleb Ji]] (UNSW)
- [[Ian Le]] (ANU)
- [[Oliver Li]] (Melbourne)
- Yixuan Li (ANU)
- Svetlana Makarova (ANU)
- Scott Mullane (Melbourne)
- Uri Onn (ANU)
- [[Fei Peng]] (Melbourne)
- [[Behrouz Taji]] (UNSW)
- [[Bailey Whitbread]] (Sydney)
- Yaping Yang (Melbourne)
- Gufang Zhao (Melbourne)

* Abstracts
** Dougal Davis
- Title :: Multivariate V-filtrations and the Strong Monodromy Conjecture for hyperplane arrangements
- Abstract ::
  For a hypersurface singularity \(f = 0\), the Strong Monodromy Conjecture of Igusa and Denef-Loeser proposes a surprising connection between poles of zeta functions (defined by \(p\)-adic or motivic integration of \(f\)) and zeroes of Bernstein-Sato polynomials (defined by differential equations satisfied by \(f\)). In this talk, I will discuss a proof of this conjecture when \(f\) is the equation of a hyperplane arrangement with arbitrary multiplicities. The main ingredient is a new approach to Sabbah’s theory of \(V\)-filtrations of holonomic D-modules along divisors with normal crossings, which shows that these filtrations have much better properties than was previously known. I will explain how this general theory works, and outline how the additional control it gives over Bernstein-Sato roots is used to prove the conjecture. This is joint work with Ruijie Yang.
  
** Gianluca Faraco
- Title :: Relative period relation of abelian differential on Riemann surfaces

- Abstract :: A translation surface is defined by an abelian differential on a Riemann surface. Every such pair determines a representation called the absolute period representation or period character. In this seminar we discuss the realisation problem of whether a given representation to arise as the period character of some translation surface, possibly with prescribed data such as the order of singularities, spin structure and hyperelliptic structure. Next we focus on the subtle problem of prescribing the so-called relative periods, thereby answering a question posed by Simion Filip. This is joint work with Dawei Chen.

** Christian Haesemeyer
- Title :: On the higher algebraic K-theory of toric varieties
- Abstract ::
  (Split) toric varieties are given by combinatorial data that can be encoded, for example, in an object called a monoid scheme (a scheme built out of commutative monoids). I will report on some ongoing work with Weibel regarding the K-theory of monoid schemes, and explain how it determines that of the associated toric varieties.

** Caleb Ji
- Title :: Triangular modular curves and regular polyhedra over finite fields
- Abstract :: Triangular modular curves, introduced by Clark and Voight, give a variant of modular curves by replacing \(\operatorname{PSL}_2(\mathbf{Z})\) with triangle groups \(\Delta(a,b,c)\).  In the case that \(a=2\), we give a classification of these triangular modular curves.  Using Clifford algebras, such curves are naturally associated with Grothendieck's regular polyhedra over finite fields.  Our classification thus answers one of Grothendieck's questions regarding these polyhedra.

** Ian Le
- Title :: Quasi-algebraic braids
- Abstract ::
  I will talk about some joint work in progress with Konstantin Jakob and Masoud Kamgarpour in which we define quasi-algebraic braids. These are braids coming from maps of formal loops (\(\operatorname{Spec} \mathbf{C}((t))\)) into a hyperplane complement.  These arise naturally in two ways: 1) as links of singularities of plane curves 2) as Stokes data for irregular singularities. It turns out that algebraic braids are quite a restrictive class. I'll give explain a complete 
classification/construction of them.

** Oliver Li
- Title :: Pseudo-coherent complexes on algebraic stacks.

- Abstract :: Let \(f \colon X \to Y\) be a proper morphism of locally noetherian schemes. Grothendieck's coherence theorem is the statement that \(R^if_*\) sends coherent sheaves to coherent sheaves. In this talk, I will discuss suitable adaptations of this result to the setting of non-noetherian algebraic stacks. This is joint work in progress with Jack Hall.
** Fei Peng
- Title :: Towards projective coarse moduli spaces of stable super Riemann surfaces

- Abstract :: Super Riemann surfaces play a central role in algebraic supergeometry. In this talk, I will present a stack-theoretic construction of the moduli spaces of stable super Riemann surfaces. The key ingredient is a generalized Keel–Mori theorem on the existence of coarse moduli spaces in the super setting. I will explain how this applies to stable super Riemann surfaces and discuss ongoing questions regarding the projectivity of the resulting coarse moduli spaces.

** Behrouz Taji
- Title :: Moduli construction for higher dimensional varieties through Hodge theory and GIT

- Abstract :: Deligne–Mumford showed that the geometric notion of stability for curves is intimately connected to GIT‑stability of the corresponding Hilbert‑scheme points (for a suitable choice of linearization). Mumford's construction of the coarse moduli space of stable curves as a GIT‑quotient follows directly from this relationship. In higher dimensions, KSB‑stable varieties, discovered by Kollár and Shepherd-Barron, play the role of stable curves. However, “standard’’ linearizations are known to fail in realizing their coarse moduli space as a GIT‑quotient. Kollár therefore asks whether alternative linearizations might still produce such quotients. We give an affirmative answer: with an appropriate choice of linearization, KSB‑stability implies GIT‑stability. This is based on joint work with S. Kovács.

** Bailey Whitbread
- Title :: The Deligne-Simpson problem, braid stacks, and computers
- Abstract ::
  This talk is centred on an old problem about matrices, known as the Deligne–Simpson problem. We will discuss a modern geometric version, called the irregular Deligne–Simpson problem. In joint work with Masoud Kamgarpour, we resolve the irregular Deligne–Simpson problem in many cases by exploiting a connection with the world of braids and braid stacks. I will also discuss how Julia and Codex can contribute to mathematical research.

* Schedule

TBA

* Registration

If you want to attend, please [[mailto:anand.deopurkar@anu.edu.au?subject=%5BAlgemel26%5D%20Interest%20in%20attending&body=I%20would%20like%20to%20attend%20Algebraic%20Geometry%20in%20Melbourne%20in%20July%202026.%20%20Thanks!][send an email to the organiser at ANU.]]
If you are a student or an early career researcher, please indicate if you need financial support. 
We may be able to provide a limited amount.

* Organisers
:PROPERTIES:
:UNNUMBERED: notoc
:END:

- Anand Deopurkar (ANU)
- Jack Hall (Melbourne)
- Paul Norbury (Melbourne)

* Thanks
:PROPERTIES:
:UNNUMBERED: notoc
:END:
We are supported in part by funds from the Australian Research Council.

